// Copyright (c) 2026 cloud-boot contributors
// SPDX-License-Identifier: GPL-2.0-only
//
// harvest-reference is the R-doom1g provable-protocol oracle generator.
//
// It runs the gore engine HEADLESS, in deterministic mode (tic-locked
// clock + fixed PRNG seed), with a SCRIPTED input sequence supplied via
// flags, and snapshots the framebuffer + PRNG state + frame-hash at
// every declared checkpoint tic. The resulting files under -out form
// the reference oracle that internal/livedoomboot/provable_test.sh
// compares against on every CI run.
//
// Reproducibility contract (the whole point):
//
//   - Same WAD bytes + same -seed + same -script + same gore commit
//     ==> identical oracle bytes (PPM + JSON + SHA-256).
//   - If the WAD or gore commit changes, the oracle is regenerated by
//     re-running this command; the resulting diff in the oracle/
//     directory is committed atomically with the engine/WAD bump, so
//     every revision of the oracle is auditable in git history.
//
// Why this is provable, not empirical:
//
//   - The framebuffer at tic T is a pure function of (initial WAD,
//     seed, input sequence up to T, engine version). Two runs that
//     match on every input MUST produce byte-identical frames.
//   - The frame SHA-256 hash collapses the provability check to a
//     32-byte constant-time compare in CI.
//
// Usage:
//
//	harvest-reference \
//	    -wad embedwad/doom1.wad \
//	    -seed 0 \
//	    -script docs/oracle-script.txt \
//	    -checkpoints 105,175,350,525,1050 \
//	    -out oracle/
//
// The script file format is one event per line:
//
//	<tic>:keydown:<KEY>     # KEY is a gore.KEY_* symbol or hex
//	<tic>:keyup:<KEY>
//	<tic>:end               # tell the engine to Stop()
//
// Comments (#…) and blank lines are skipped.

package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"image"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"

	godoom "github.com/go-doom/engine"
	"github.com/go-doom/engine/backend/audiolog"
	"github.com/go-doom/engine/embedwad"
)

type checkpoint struct {
	Tic        int32  `json:"tic"`
	FrameHash  string `json:"frame_hash"` // hex SHA-256 of the RGBA pixel buffer
	FramePPM   string `json:"frame_ppm"`  // relative filename of the PPM snapshot
	PRndIndex  int32  `json:"prndindex"`
	MRndIndex  int32  `json:"mrndindex"`
	FrameCount uint64 `json:"frame_count"`
	Width      int    `json:"width"`
	Height     int    `json:"height"`
}

type manifest struct {
	Seed         uint8        `json:"seed"`
	WAD          string       `json:"wad"`
	WADBytes     int          `json:"wad_bytes"`
	WADHash      string       `json:"wad_hash"`
	ScriptHash   string       `json:"script_hash"`
	GoreVersion  string       `json:"gore_version"` // git rev embedded by harvest invocation, optional
	Checkpoints  []checkpoint `json:"checkpoints"`
	Deterministic bool        `json:"deterministic"`
}

type scriptEvent struct {
	tic   int32
	kind  string // "keydown", "keyup", "end"
	key   uint8
}

type harvestFrontend struct {
	mu sync.Mutex

	// Pending scripted events, sorted by tic.
	events     []scriptEvent
	eventIdx   int

	// Checkpoint tics, sorted ascending.
	checkTics  []int32
	nextCheck  int

	// Latest framebuffer reference (engine retains ownership, but the
	// pixel buffer is stable between DrawFrame returns).
	lastFrame  *image.RGBA
	frameCount uint64

	// Output sink for snapshots.
	outDir     string
	results    []checkpoint
	stopCalled bool

	// R-doom1h: GATE C-1 audio event recorder. Nil disables recording so
	// tests that don't need the audio log can newFrontend(nil, ..., ...).
	audio      *audiolog.Recorder
}

func newFrontend(events []scriptEvent, checkTics []int32, outDir string) *harvestFrontend {
	sort.Slice(events, func(i, j int) bool { return events[i].tic < events[j].tic })
	sort.Slice(checkTics, func(i, j int) bool { return checkTics[i] < checkTics[j] })
	return &harvestFrontend{
		events:    events,
		checkTics: checkTics,
		outDir:    outDir,
		audio:     audiolog.New(godoom.CurrentTic),
	}
}

func (f *harvestFrontend) DrawFrame(img *image.RGBA) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.frameCount++
	f.lastFrame = img

	// Use the deterministic engine tic (i_GetTime via CurrentTic) as
	// the checkpoint key, NOT f.frameCount — they differ once the
	// engine renders >1 frame per tic (it doesn't today, but the
	// contract is "checkpoint at tic T" not "at frame N").
	tic := godoom.CurrentTic()

	// Fire all checkpoints that this tic has reached.
	for f.nextCheck < len(f.checkTics) && f.checkTics[f.nextCheck] <= tic {
		target := f.checkTics[f.nextCheck]
		if err := f.snapshot(target, img); err != nil {
			fmt.Fprintf(os.Stderr, "harvest: snapshot tic=%d failed: %v\n", target, err)
		}
		f.nextCheck++
	}

	// Stop the engine once we've captured everything we asked for,
	// even if the script's explicit "end" event hasn't fired yet.
	if f.nextCheck >= len(f.checkTics) && !f.stopCalled {
		f.stopCalled = true
		godoom.Stop()
	}
}

func (f *harvestFrontend) snapshot(tic int32, img *image.RGBA) error {
	// PPM (binary P6) is the same format the provable_test.sh runner
	// receives from QEMU's QMP screendump, so byte-equal comparison is
	// trivial. We strip the alpha channel (DOOM is fully opaque) so
	// the PPM hash matches the QMP capture's pixel layout.
	w := img.Rect.Dx()
	h := img.Rect.Dy()
	rgb := make([]byte, w*h*3)
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			off := img.PixOffset(x, y)
			rgb[(y*w+x)*3+0] = img.Pix[off+0]
			rgb[(y*w+x)*3+1] = img.Pix[off+1]
			rgb[(y*w+x)*3+2] = img.Pix[off+2]
		}
	}

	hash := sha256.Sum256(rgb)
	hashHex := hex.EncodeToString(hash[:])

	ppmName := fmt.Sprintf("frame_tic%06d.ppm", tic)
	ppmPath := filepath.Join(f.outDir, ppmName)
	if err := writePPM(ppmPath, w, h, rgb); err != nil {
		return err
	}

	prnd, mrnd := godoom.RandomState()
	f.results = append(f.results, checkpoint{
		Tic:        tic,
		FrameHash:  hashHex,
		FramePPM:   ppmName,
		PRndIndex:  prnd,
		MRndIndex:  mrnd,
		FrameCount: f.frameCount,
		Width:      w,
		Height:     h,
	})
	fmt.Fprintf(os.Stderr, "harvest: tic=%d frame#%d sha256=%s prnd=%d mrnd=%d -> %s\n",
		tic, f.frameCount, hashHex[:16], prnd, mrnd, ppmName)
	return nil
}

func writePPM(path string, w, h int, rgb []byte) error {
	if len(rgb) != w*h*3 {
		return fmt.Errorf("writePPM: rgb len %d != %d", len(rgb), w*h*3)
	}
	fh, err := os.Create(path)
	if err != nil {
		return err
	}
	defer fh.Close()
	if _, err := fmt.Fprintf(fh, "P6\n%d %d\n255\n", w, h); err != nil {
		return err
	}
	_, err = fh.Write(rgb)
	return err
}

func (f *harvestFrontend) SetTitle(_ string) {}

func (f *harvestFrontend) GetEvent(ev *godoom.DoomEvent) bool {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.eventIdx >= len(f.events) {
		return false
	}
	tic := godoom.CurrentTic()
	next := f.events[f.eventIdx]
	if next.tic > tic {
		return false
	}
	f.eventIdx++
	switch next.kind {
	case "keydown":
		ev.Type = godoom.Ev_keydown
		ev.Key = next.key
	case "keyup":
		ev.Type = godoom.Ev_keyup
		ev.Key = next.key
	case "end":
		if !f.stopCalled {
			f.stopCalled = true
			godoom.Stop()
		}
		return false
	default:
		return false
	}
	return true
}

func (f *harvestFrontend) CacheSound(name string, data []byte) {
	if f.audio != nil {
		f.audio.Cache(name, data)
	}
}

func (f *harvestFrontend) PlaySound(name string, channel, vol, sep int) {
	if f.audio != nil {
		f.audio.Play(name, channel, vol, sep)
	}
}

func parseScript(rd io.Reader) ([]scriptEvent, []byte, error) {
	data, err := io.ReadAll(rd)
	if err != nil {
		return nil, nil, err
	}
	var out []scriptEvent
	for ln, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if i := strings.Index(line, "#"); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, ":", 3)
		if len(parts) < 2 {
			return nil, nil, fmt.Errorf("line %d: malformed (want tic:kind[:key]): %q", ln+1, line)
		}
		for i := range parts {
			parts[i] = strings.TrimSpace(parts[i])
		}
		tic, err := strconv.ParseInt(parts[0], 10, 32)
		if err != nil {
			return nil, nil, fmt.Errorf("line %d: bad tic %q: %w", ln+1, parts[0], err)
		}
		evt := scriptEvent{tic: int32(tic), kind: parts[1]}
		switch evt.kind {
		case "end":
			// OK
		case "keydown", "keyup":
			if len(parts) != 3 {
				return nil, nil, fmt.Errorf("line %d: %s requires a key", ln+1, evt.kind)
			}
			k, err := parseKey(parts[2])
			if err != nil {
				return nil, nil, fmt.Errorf("line %d: %w", ln+1, err)
			}
			evt.key = k
		default:
			return nil, nil, fmt.Errorf("line %d: unknown kind %q", ln+1, evt.kind)
		}
		out = append(out, evt)
	}
	return out, data, nil
}

func parseKey(s string) (uint8, error) {
	s = strings.TrimSpace(s)
	// Hex passthrough: 0x42 / 0X42
	if strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X") {
		v, err := strconv.ParseUint(s[2:], 16, 8)
		if err != nil {
			return 0, fmt.Errorf("bad hex key %q: %w", s, err)
		}
		return uint8(v), nil
	}
	// Symbolic names — the small set the test runner needs.
	switch strings.ToUpper(s) {
	case "ENTER", "KEY_ENTER":
		return godoom.KEY_ENTER, nil
	case "ESC", "ESCAPE", "KEY_ESCAPE":
		return godoom.KEY_ESCAPE, nil
	case "UP", "KEY_UPARROW":
		return godoom.KEY_UPARROW1, nil
	case "DOWN", "KEY_DOWNARROW":
		return godoom.KEY_DOWNARROW1, nil
	case "LEFT", "KEY_LEFTARROW":
		return godoom.KEY_LEFTARROW1, nil
	case "RIGHT", "KEY_RIGHTARROW":
		return godoom.KEY_RIGHTARROW1, nil
	case "FIRE", "KEY_FIRE":
		return godoom.KEY_FIRE1, nil
	case "USE", "SPACE":
		return godoom.KEY_USE1, nil
	case "TAB":
		return godoom.KEY_TAB, nil
	}
	// Plain decimal.
	v, err := strconv.ParseUint(s, 10, 8)
	if err != nil {
		return 0, fmt.Errorf("unknown key %q (want symbol, 0xHH, or decimal)", s)
	}
	return uint8(v), nil
}

func parseCheckpoints(s string) ([]int32, error) {
	if strings.TrimSpace(s) == "" {
		return nil, errors.New("-checkpoints must be a non-empty comma list")
	}
	var out []int32
	for _, p := range strings.Split(s, ",") {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		v, err := strconv.ParseInt(p, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("bad checkpoint %q: %w", p, err)
		}
		out = append(out, int32(v))
	}
	if len(out) == 0 {
		return nil, errors.New("no valid checkpoints parsed")
	}
	return out, nil
}

func run(args []string, stderr io.Writer) error {
	fs := flag.NewFlagSet("harvest-reference", flag.ContinueOnError)
	fs.SetOutput(stderr)
	wadPath := fs.String("wad", "embedwad/doom1.wad", "path to DOOM WAD")
	wadName := fs.String("wad-name", "doom1.wad", "name to advertise the WAD as via embedwad.New")
	seed := fs.Uint("seed", 0, "PRNG seed (0..255)")
	scriptPath := fs.String("script", "", "scripted input file (empty = no input)")
	checkpointsCSV := fs.String("checkpoints", "1,35,70,140,1050",
		"comma-separated list of tics to snapshot")
	outDir := fs.String("out", "oracle", "output directory for oracle artifacts")
	goreVersion := fs.String("gore-version", "", "engine commit/tag to record in manifest")
	// R-doom1h: when -verify-audio-log is set, the run is a re-harvest in
	// audit mode — write a fresh audio_log.json into -out as usual, then
	// byte-compare it against the path provided. Exit non-zero on diff.
	verifyAudioLog := fs.String("verify-audio-log", "",
		"path to a committed audio_log.json; after harvest, byte-compare the fresh log against it and fail on diff")
	if err := fs.Parse(args); err != nil {
		return err
	}

	wadBytes, err := os.ReadFile(*wadPath)
	if err != nil {
		return fmt.Errorf("read WAD: %w", err)
	}
	wadHash := sha256.Sum256(wadBytes)

	var (
		events     []scriptEvent
		scriptRaw  []byte
		scriptHash [32]byte
	)
	if *scriptPath != "" {
		fh, err := os.Open(*scriptPath)
		if err != nil {
			return fmt.Errorf("open script: %w", err)
		}
		events, scriptRaw, err = parseScript(fh)
		fh.Close()
		if err != nil {
			return fmt.Errorf("parse script: %w", err)
		}
		scriptHash = sha256.Sum256(scriptRaw)
	}

	checkTics, err := parseCheckpoints(*checkpointsCSV)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir out: %w", err)
	}

	fs2 := embedwad.New(*wadName, wadBytes)
	godoom.SetVirtualFileSystem(fs2)
	godoom.EnableQuitting(false)
	godoom.SetDeterministicTics(true)
	godoom.ResetClock()
	godoom.SeedRandom(uint8(*seed & 0xff))

	fe := newFrontend(events, checkTics, *outDir)

	fmt.Fprintf(stderr, "harvest: wad=%s (%d bytes, sha256=%s) seed=%d checkpoints=%v\n",
		filepath.Base(*wadPath), len(wadBytes),
		hex.EncodeToString(wadHash[:])[:16], *seed, checkTics)

	// gore.Run is blocking; the frontend triggers Stop() once all
	// checkpoints have been captured (or via the script "end" event).
	godoom.Run(fe, []string{"-iwad", *wadName})

	man := manifest{
		Seed:          uint8(*seed & 0xff),
		WAD:           filepath.Base(*wadPath),
		WADBytes:      len(wadBytes),
		WADHash:       hex.EncodeToString(wadHash[:]),
		ScriptHash:    hex.EncodeToString(scriptHash[:]),
		GoreVersion:   *goreVersion,
		Checkpoints:   fe.results,
		Deterministic: true,
	}
	manBlob, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return err
	}
	manPath := filepath.Join(*outDir, "manifest.json")
	if err := os.WriteFile(manPath, append(manBlob, '\n'), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}
	fmt.Fprintf(stderr, "harvest: wrote %d checkpoints + manifest -> %s\n",
		len(fe.results), manPath)

	audioPath := filepath.Join(*outDir, "audio_log.json")
	if err := writeAudioLog(audioPath, fe.audio); err != nil {
		return fmt.Errorf("write audio log: %w", err)
	}
	fmt.Fprintf(stderr, "harvest: wrote %d audio events -> %s\n",
		len(fe.audio.Entries()), audioPath)

	if *verifyAudioLog != "" {
		if err := compareAudioLogs(*verifyAudioLog, audioPath, stderr); err != nil {
			return err
		}
	}
	return nil
}

// writeAudioLog serialises the recorder to audio_log.json. Extracted so
// the unit tests can exercise the write+compare paths without spinning
// up gore.Run.
func writeAudioLog(path string, rec *audiolog.Recorder) error {
	fh, err := os.Create(path)
	if err != nil {
		return err
	}
	defer fh.Close()
	return rec.WriteJSON(fh)
}

// compareAudioLogs reads two audio_log.json files and reports any byte
// difference. The committed log is the oracle; the fresh log is what
// the current engine produced. Byte-equal is the GATE C-1 contract.
func compareAudioLogs(oraclePath, freshPath string, stderr io.Writer) error {
	a, err := os.ReadFile(oraclePath)
	if err != nil {
		return fmt.Errorf("read oracle audio log: %w", err)
	}
	b, err := os.ReadFile(freshPath)
	if err != nil {
		return fmt.Errorf("read fresh audio log: %w", err)
	}
	if bytes.Equal(a, b) {
		ah := sha256.Sum256(a)
		fmt.Fprintf(stderr, "harvest: GATE C-1 PASS audio_log.json sha256=%s\n",
			hex.EncodeToString(ah[:])[:16])
		return nil
	}
	ah := sha256.Sum256(a)
	bh := sha256.Sum256(b)
	return fmt.Errorf("GATE C-1 FAIL: audio_log.json byte mismatch — oracle=%s fresh=%s",
		hex.EncodeToString(ah[:])[:16], hex.EncodeToString(bh[:])[:16])
}

func main() {
	if err := run(os.Args[1:], os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "harvest:", err)
		os.Exit(1)
	}
}
